### ISSUE TITLE
convert_to_csv.py does not work under windwos due to ":" in the csv paths

### ISSUE THREAD

**Issue by mr15** [emoncms/usefulscripts#39]
When running this script under Windows, I get the following error:
> D:\Dateien\Dokumente\pyEmonCmsDownload>python.exe -m convert_to_csv.py
Converting phpfina feed 104076
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "D:\Dateien\Dokumente\pyEmonCmsDownload\convert_to_csv.py", line 57, in <module>
    phpfina_convert(username+"/phpfina/",username+"/csv/",f['id'],f['tag'],f['name'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dateien\Dokumente\pyEmonCmsDownload\convert_to_csv.py", line 22, in phpfina_convert
    csv_fh = open(csvdir+str(feedid)+"-"+str(tag)+"-"+str(name)+".csv","w")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'niclas/csv/104076-Node:0-node:0:Z1_Temp01-T_DHW_oben.csv'

I think this is due to windows not allowing ":" in file names.

My proposal for a fix: Replace ":" with "-".

**Comment by mr15** [comment]
I created PR #40 for this proposed fix.
